Algoritmo "desafio"

Var
ano, nasc, idade: Inteiro

Inicio
Escreva (" Em que ano nós estamos: ")
Leia(ano)
Escreva (" Em que ano voce nasceu: ")
Leia(nasc)
idade <- ano - nasc
EscrevaL (" Em ", ano , " Lucas terá ", idade , " anos ")
Se (idade >= 18) entao
   EscrevaL (" Lucas estará apto a servir o exercito Brasileiro ")
Senao
     EscrevaL (" Lucas não estará apto a servir o exercito Brasileiro ")
FimSe



Fimalgoritmo
