Algoritmo "desafio"

Var
ano, nasc, idade: Real

Inicio
Escreva (" Em que ano nós estamos?? ")
Leia(ano)
Escreva (" Em que ano voce nasceu?? ")
Leia(nasc)
idade <- ano - nasc
Escreval (" Em ", ano , " Lucas terá ", idade, " anos ")
Se (idade >= 18) então
   Escreval (" ::Lucas estar apto pra servir o exercito Brasileiro:: ")
Senao
     Escreval (" ::Lucas não estar apto para servir o exercito Brasileiro:: ")
FimSe




Fimalgoritmo