Algoritmo "Depatamento)

Var
ano, nasc, idade: Real

Inicio
Escreva (" Ano atual (yyyyy) : ")
Leia(ano)
Escreva (" Ano do meu nascimento (yyyy) : ")
Leia(nasc)
idade <- ano - nasc
Escreval (" Em ", ano , " Lucas terá ", idade , " anos!! ")
Se (idade >= 18) então
   Escreva (" Logo, Lucas estar apto para tirar a carteira ")
Senao
     Escreva (" Logo, Lucas estar inapto para tirar a carteira ")
FimSe



Fimalgoritmo
